// Top-level build file

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:<your-AGP-version>"
        classpath "com.google.gms:google-services:4.3.15"
    }
}

// No pluginManagement{} here!
// No allprojects { repositories { … } } here!

plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.kotlin.jvm)      apply false
    id("com.google.gms.google-services") version "4.4.2" apply false
}
