
pluginManagement {
    // Declare plugin repositories and plugin versions here
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }

}

dependencyResolutionManagement {
    // Only use the repositories declared in this block
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

rootProject.name = "cs499_weighttracker_pn"
include(":app")

